export const ActionTypes = {
    DEPOSITAR: "DEPOSITAR",
    RETIRAR: "RETIRAR",
    SET_POKEMONS: "SET_POKEMONS",
    SELECTED_POKEMON: "SELECTED_POKEMON",
    UPDATE_POKEMON: "UPDATE_POKEMON",
    REMOVED_POKEMON: "REMOVED_POKEMON",
};